# Obfuscated by PyLockWare Obfuscator

import sys
sys.tracebacklimit = 0

"""
Builtin Dispatcher Module
Generated by PyLockWare Obfuscator
"""


class _QD3VDfMqCxbgXVpQQKJBPE4nqnJ3jZXN:
    """Central dispatcher for built-in functions"""
    _builtins = {
    '_6csHJRsH5tv1CzCEipGVrROo9tbCxmyS': abs,
    '_WFmJ48torWsWeinEGNN42fmcld958RCq': all,
    '_s6sC1BpiOm4Mrjmd7nxQ7wfvqvfuyIwD': any,
    '_W35gieJyBX3zyqcWWyZQdTDnvko0gzND': bool,
    '_5x7EEYVfKtwe0Szn9UMnFybb9fGEYcDT': chr,
    '_fOTnDkRKMZYrhrsiuEK0VnDH1wFWPOMk': float,
    '_C7BnXn35iEh511bGFi1pb6LyPbgSL97F': globals,
    '_JdE7glIo4wkfSUORDYASMF96DO7LZXtL': hash,
    '_1PskIx1pe3cHMaJ40YH5bpDd9ATMKQEg': id,
    '_33XcoX1yz5YVJ98ZrAZedF3jQM6ciP1i': int,
    '_AiMgqJx4mVkznE499O29QyypZNc4rhYe': isinstance,
    '_3d3tf48fOycqKjL2xGWFePWxKPoMTEUd': iter,
    '_4L7VbRetmp7w2bQh6o89f5AELY8npmlV': len,
    '_iJaX9gqHQRQXVDgdXAYKInsmM2tAwiaU': list,
    '_VJxQMZUi1ntz60UBQr9JhxoWMcL3KpYE': max,
    '_P3yFSWrOnhUIFXM1lTqBu44V8tnqPAJB': min,
    '_A1l7oF2P40oGfSPZQwoNLFSqSmkO6AF3': next,
    '_hphjdyoE5BfMIRS7zA913RLi4rqegddg': ord,
    '_ZBUUElCf1IE59zejdF4slb61bBYqcbGc': pow,
    '_zWEDmGa8X6vRsLfMXruTjFRpjSoyxsDS': print,
    '_3ONLiPPBCcUQ8T1q4xWJiFJhlR7vxgCP': property,
    '_ZbDpq51qJyY0uuNuctyErER6FeJ2lqmH': range,
    '_LcpVIBVUGsA2mmQUcNAtJZcYHnRbLBIf': str,
    '_FBWO8p2MpJa5CABV39xckkQOORt0ffeJ': sum,
    }

    def __getattr__(self, name):
        if name in self._builtins:
            return self._builtins[name]
        raise AttributeError(f"Unknown builtin: {name}")


# Global dispatcher instance
_qd3vdfmqcxbgxvpqqkjbpe4nqnj3jzxn = _QD3VDfMqCxbgXVpQQKJBPE4nqnJ3jZXN()
